version: '3.8'
services:
  vgg_service:
    build: ./music_class
    ports:
      - "5000:5000"
    networks:
      - app-network
  svm_service:
    build: ./back SVM/SVM
    ports:
      - "5001:5001"
    networks:
      - app-network    
  frontend:
    build: ./front
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
